# Generated by Django 3.0.3 on 2020-02-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email_0',
        ),
    ]
